# Generated by Django 3.1.4 on 2021-02-18 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='phone',
            field=models.CharField(default=0, max_length=111),
            preserve_default=False,
        ),
    ]
